version: '3.8'

services:
  knapsack:
    build:
      context: ./docker/
      dockerfile: Dockerfile
    container_name: knapsack-container
    volumes:
      - .:/workspace
    tty: true
    stdin_open: true